using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BlogApp.Models;

namespace BlogApp.Controllers;

public class BlogController : Controller
{
    private readonly ILogger<HomeController> _logger;

    
    public IActionResult Index()
    {
        var blogposts = new List<Blog> {
            
            new Blog {Title ="Blog - 1",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 2",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 3",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 4",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 5",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 6",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 7",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 8",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 9",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            new Blog {Title ="Blog - 10",
             Summary = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum quam tortor, ut efficitur ante tincidunt in. Cras pharetra consequat sagittis. Nullam elit quam, rutrum vitae sagittis ut, lacinia sit amet est. Duis volutpat fermentum fringilla. Proin lacinia eu ligula sed ullamcorper. Cras et est felis. Nunc suscipit mauris sit amet dolor condimentum ultrices sit amet at mi. Cras metus erat, convallis in hendrerit ac, congue ac lectus. Sed id vestibulum turpis, nec tempus lorem. Integer eget blandit metus, vitae feugiat sapien. Phasellus mattis magna mauris. Quisque scelerisque tincidunt massa ut tempor. Fusce iaculis, ex quis auctor malesuada, nibh lectus aliquam quam, vel placerat elit mi at lorem. In congue, erat a gravida pellentesque, eros ante vulputate dui, sit amet luctus tortor dolor eu magna. Mauris dictum odio placerat nisl laoreet faucibus.",
             Images = "https://picsum.photos/seed/picsum/200/300"},
            
        };
        return View(blogposts);
    }

}
